### PR TITLE
Print parameter documentation in the order its defined in

### PR DESCRIPTION
**Pull request by brendanlong**
I changed the parameter info to be stored in Lists instead of Maps so we get it in the same order it was defined in. The previous version displayed parameters in arbitrary order, and we never look up parameters by name anyway.

Are the size of my pull requests ok or would prefer that I do them in larger chunks?

### CODE REVIEW

**Comment by brendanlong** [comment]
Apparently this just automatically adds everything I do anyway, so I guess the length is just based on how much I do.

**Comment by FroMage** [comment]
Hey this is great, thanks. Can you explain the exclude taglet though? Is this a new feature? If yes can you add documentation for it please?

**Comment by FroMage** [comment]
Note that #28 already has support for filtering but as a command-line.

**Comment by brendanlong** [comment]
The @exclude taglet would be a new feature. I think it's generally more useful than a command-line option, since a command-line option has to be put in every time, while @exclude only needs to be added once.

**Comment by brendanlong** [comment]
I'll write some documentation for it on Monday probably.

**Comment by brendanlong** [comment]
I added some documentation for @exclude.

**Comment by FroMage** [comment]
Thanks a lot!

**Pull request merged**
