### PR TITLE
Support parameterized types for wrapped values

### PR DESCRIPTION
**Pull request by matsli**

### CODE REVIEW

**Comment by FroMage** [comment]
What's this for?

**Comment by matsli** [comment]
@returnWrapped with generic types worked fine in 0.10.0 but does not work in master.
When using the master version, the type parameter is lost.

Example that worked before:

/**
     \* List all shops.
     \* 
     \* @return list of shops
     \* @returnWrapped java.util.List&lt;se.dekra.bb.domain.asset.Shop&gt;
     */

**Comment by FroMage** [comment]
Mmm, this is weird, and your fix is weird too. I need to look at this in more details.

**Comment by matsli** [comment]
Yes, I probably should have raised an issue first. Sorry about that.

**Comment by FroMage** [comment]
It's OK, I was just wondering what it was about ;)

**Comment by matsli** [comment]
I did som further research. This is the commit that removed support for generics: db9ca4741ce21e0382e2754a1f4f341b75764742
So generics were previously handled in MethodWriter but that code was removed.

**Comment by FroMage** [comment]
Damn, looks like you're right. Do you think you can put them back in there?

**Comment by matsli** [comment]
Yes, if you prefer to have it there. There are some benefits in letting JaxType return something that looks like a real generic type since you then can use the same printing code as for other generic types. However, my fix won't render any type parameters of unknown type and that's a drawback.

**Comment by matsli** [comment]
I have reverted my fix and backported the old support for generics

**Comment by FroMage** [comment]
Thanks!

**Pull request merged**
